package create

import (
	"os"
	"path/filepath"
)

// namespaceContent content of the file
const namespaceContent = "# Generated by roxygen2: do not edit by hand\n"

// namespace holds the information on the NAMESPACE file
func namespace(meta PackageMetadata) error {
	s := files.NAMESPACE
	if err := os.WriteFile(filepath.Join(meta.Dir, s), []byte(namespaceContent), 0644); err != nil {
		return err
	}
	return inform(s)
}
