name: Fast-forward main from release/prod

on:
  workflow_run:
      workflows: ["Release Go CLI"]
      types:
        - completed

jobs:
  create-pr:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'release/prod'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch origin

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TINYRDEV_PAT }}
          base: main
          branch: release/prod
          title: 'Merge release into main'
          body: |
            This PR was automatically created by GitHub Actions to merge the latest changes from `release` into `main`.
          draft: false
          delete-branch: false
